"""Project context — generates and caches a CLAUDE.md for agent worktrees.

First agent (planner or developer) explores the codebase and writes a
project context summary. Subsequent agents get this injected into their
worktree as CLAUDE.md, skipping expensive codebase exploration.
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

log = logging.getLogger("warchief.project_context")

_CONTEXT_FILE = "project-context.md"


def get_context_path(project_root: Path) -> Path:
    return project_root / ".warchief" / _CONTEXT_FILE


def has_project_context(project_root: Path) -> bool:
    return get_context_path(project_root).exists()


def read_project_context(project_root: Path) -> str:
    path = get_context_path(project_root)
    if not path.exists():
        return ""
    try:
        return path.read_text()
    except OSError:
        return ""


def write_project_context(project_root: Path, content: str) -> None:
    path = get_context_path(project_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    log.info("Wrote project context (%d chars) to %s", len(content), path)


def generate_project_context(project_root: Path) -> str:
    """Auto-generate project context by scanning the codebase.

    This is a fast, zero-LLM-cost scan that extracts structure
    and patterns from the filesystem and config files.
    """
    sections: list[str] = []

    sections.append("# Project Context\n")
    sections.append("Auto-generated by Warchief. Agents read this to skip codebase exploration.\n")

    # Project structure (top 2 levels)
    try:
        result = subprocess.run(
            [
                "find",
                ".",
                "-maxdepth",
                "2",
                "-not",
                "-path",
                "./.git/*",
                "-not",
                "-path",
                "./node_modules/*",
                "-not",
                "-path",
                "./.warchief/*",
                "-not",
                "-path",
                "./.warchief-worktrees/*",
                "-not",
                "-path",
                "./.venv/*",
                "-not",
                "-path",
                "./.next/*",
                "-not",
                "-path",
                "./dist/*",
                "-not",
                "-name",
                "__pycache__",
                "-not",
                "-name",
                ".DS_Store",
            ],
            cwd=project_root,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            tree = result.stdout.strip()
            sections.append(f"## Project Structure\n```\n{tree}\n```\n")
    except (subprocess.TimeoutExpired, OSError):
        pass

    # Detect framework from config files
    frameworks: list[str] = []
    p = project_root

    if (p / "package.json").exists():
        try:
            import json

            pkg = json.loads((p / "package.json").read_text())
            deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
            if "react" in deps:
                frameworks.append("React")
            if "vue" in deps:
                frameworks.append("Vue")
            if "svelte" in deps:
                frameworks.append("Svelte")
            if "next" in deps:
                frameworks.append("Next.js")
            if "nuxt" in deps:
                frameworks.append("Nuxt")
            if "express" in deps:
                frameworks.append("Express.js")
            if "fastify" in deps:
                frameworks.append("Fastify")
            if "vitest" in deps:
                frameworks.append("Vitest (testing)")
            if "jest" in deps:
                frameworks.append("Jest (testing)")
            if "playwright" in deps or "@playwright/test" in deps:
                frameworks.append("Playwright (E2E)")
            if "prisma" in deps or "@prisma/client" in deps:
                frameworks.append("Prisma ORM")
            if "tailwindcss" in deps:
                frameworks.append("Tailwind CSS")
            if "typescript" in deps:
                frameworks.append("TypeScript")

            scripts = pkg.get("scripts", {})
            if scripts:
                sections.append(
                    "## npm Scripts\n"
                    + "\n".join(f"- `{k}`: `{v}`" for k, v in scripts.items())
                    + "\n"
                )
        except (json.JSONDecodeError, OSError):
            pass

    if (p / "pyproject.toml").exists():
        frameworks.append("Python")
        try:
            content = (p / "pyproject.toml").read_text()
            if "django" in content.lower():
                frameworks.append("Django")
            if "flask" in content.lower():
                frameworks.append("Flask")
            if "fastapi" in content.lower():
                frameworks.append("FastAPI")
            if "pytest" in content.lower():
                frameworks.append("pytest (testing)")
        except OSError:
            pass

    if (p / "go.mod").exists():
        frameworks.append("Go")
    if (p / "Cargo.toml").exists():
        frameworks.append("Rust")
    if (p / "pom.xml").exists():
        frameworks.append("Java (Maven)")
    if (p / "build.gradle").exists():
        frameworks.append("Java (Gradle)")

    if frameworks:
        sections.append("## Tech Stack\n" + ", ".join(frameworks) + "\n")

    # Detect test setup
    test_dirs = []
    for test_dir in ["tests", "test", "__tests__", "spec"]:
        if (p / test_dir).is_dir():
            test_dirs.append(test_dir)
    if test_dirs:
        sections.append("## Test Directories\n" + ", ".join(f"`{d}/`" for d in test_dirs) + "\n")

    # Check for existing CLAUDE.md (user's own project instructions)
    user_claude_md = p / "CLAUDE.md"
    if user_claude_md.exists():
        try:
            user_content = user_claude_md.read_text()
            if len(user_content) < 5000:
                sections.append(f"## Project Instructions (from CLAUDE.md)\n{user_content}\n")
        except OSError:
            pass

    return "\n".join(sections)


def install_context_in_worktree(project_root: Path, worktree_path: Path) -> None:
    """Copy project context into a worktree as CLAUDE.md.

    If no project context exists yet, generate one automatically.
    """
    if not has_project_context(project_root):
        context = generate_project_context(project_root)
        if context.strip():
            write_project_context(project_root, context)

    context = read_project_context(project_root)
    if not context:
        return

    # Write as CLAUDE.md in the worktree root
    target = worktree_path / "CLAUDE.md"
    # Don't overwrite if the project already has a CLAUDE.md checked into git
    if target.exists():
        try:
            existing = target.read_text()
            # Append project context if not already there
            if "Auto-generated by Warchief" not in existing:
                target.write_text(existing + "\n\n---\n\n" + context)
        except OSError:
            pass
    else:
        target.write_text(context)
